---
title: "Problem Set 0"
author: "Jaden Witte-Schrock"
date: "2023-09-07"
output: 
    html_document:
        theme: journal
    pdf_document: 
        latex_engine: xelatex
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1
As an economics major, I find myself interested in the fields of Public Economics and Political Economy after my time studying abroad at the London School of Economics and Political Science. I am taking this class for two reasons: 1) I needed to take a 300 level economics class this semester and this was only one of two that I qualify for and 2) I am not the most confident in my coding or data skills and will need to refine them in order to do my senior thesis in a topic that is ideally related in the realm of Public Economics or Political Economy. On that basis, I am not completely sure of what I want my final research project to be, but it would be one of those two topics that may assist me in the chosen research question of my thesis next semester. My goals for this class are to learn the basics of R, GitHub, and coding in general as well as build a strong foundational knowledge of data science that I can utilize in my thesis. After graduation, I am not entirely sure of what I will be doing, but I am casting a wide net and applying for jobs related to law, asset management, and management consulting as well as graduate school in international relations or political economy, as well as an English Teaching Fulbright Scholarship in Poland. Long term, it would be a dream of mine to work in the foreign service or a related field. 

## Section 2
\[ a^2 + b^2 = c^2 \]