---
title: Big Data and Economics
subtitle: Machine Learning and Text Applications
author: Kyle Coombs
date: "Bates College | [ECON/DCS 368](https://github.com/big-data-and-economics)"
output: 
  github_document:
    html_preview: false
    toc: true
    toc_depth: 3
    fig_width: 5
    fig_height: 5
    dev: jpeg
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center", fig.width=6, fig.height=4, 
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T,#, echo=F, warning=F, message=F
  warning=F)
if (!require(pacman)) install.packages(pacman)
pacman::p_load(tidytext,janeaustenr,textdata,stringr,tidyverse,tm,topicmodels)
theme_set(theme_minimal())
```

# Class updates

- By next class, sign up for your class presentations in the groups I assigned on the presentations pgae
  - Class presentations will be 20 minutes long and explore a data science/econ topic in more depth

- Hackathon is happening
  - Hackathon will be a two-day competition in which you work in teams of three to solve a data science problem for the city of Lewiston
  - Jacqueline Crucet will visit the class on 9/26 to give some context on the problem
  - Vote on the Discussions page!

- I added my policy on posting to GitHub to the [Discussions page](https://github.com/orgs/big-data-and-economics/discussions/3)
  - tl;dr: Post thoughtfully

- Exercise 0 Part 0 is "due" today (basically, installation steps and SSH key creation)

- Exercise 0 Part 1 is due next week (bit of a catchall for demoing Git, RStudio, etc.)

- More exercises will be posted in the coming weeks

- Problem Set 1 will be assigned next week

- Questions on: 
  - GitHub course page?
  - Syllabus and course policies? (Make note of regrading policy.)
  - Grading? 
  - GitHub Education?


